spring:
  application:
    name: crew-messaging
  profiles:
    active: host

  jackson:
    default-property-inclusion: non-null
  output:
    ansi:
      enabled: never
server:
  error:
    include-stacktrace: never
    
logging:
  level:
    root: info
    org.springframework.beans: error
    org.springframework.context: error
    org.springframework.transaction: error
    org.springframework.transaction.interceptor: error
    org.springframework.web: error
    org.hibernate: error
  pattern:
    console: '%black(%d{yyyy-MM-dd HH:mm:ss}) %green(%-5level) %cyan(%-40.40logger{40}) - %msg%n'
    